'use client';

import { type ReactNode } from 'react';
import { V2ConsoleContext, type V2ConsoleContextValue } from './V2ConsoleContext';
import { useV2ConsoleEffects } from './useV2ConsoleEffects';
import { useV2ConsoleDerivedData } from './useV2ConsoleDerivedData';
import { useV2ConsoleLocalState } from './useV2ConsoleLocalState';
import { useV2ProviderActions } from './useV2ProviderActions';
import type { ConsoleSection } from '../types';

export function V2ConsoleProvider({
  section,
  children,
}: {
  section: ConsoleSection;
  children: ReactNode;
}) {
  const {
    projectId,
    setProjectId,
    environmentId,
    setEnvironmentId,
    suiteId,
    setSuiteId,
    selectedRunId,
    setSelectedRunId,
    suiteSearch,
    setSuiteSearch,
    suiteTypeFilter,
    setSuiteTypeFilter,
    tab,
    setTab,
    busy,
    setBusy,
    error,
    setError,
    notice,
    setNotice,
    openSheet,
    setOpenSheet,
    projectDraft,
    setProjectDraft,
    openApiDraft,
    setOpenApiDraft,
    suiteDraft,
    setSuiteDraft,
    envDraft,
    setEnvDraft,
    aiDraft,
    setAiDraft,
    memberDraft,
    setMemberDraft,
    profileDraft,
    setProfileDraft,
    orgDraft,
    setOrgDraft,
    membershipEdit,
    setMembershipEdit,
    tokenDraft,
    setTokenDraft,
    flowDraft,
    setFlowDraft,
    aiOutput,
    setAiOutput,
    cleanupDays,
    setCleanupDays,
    cleanupResult,
    setCleanupResult,
    validation,
    setValidation,
    approvedAiPatch,
    setApprovedAiPatch,
    wizardOpen,
    setWizardOpen,
    suitePreviewOpen,
    setSuitePreviewOpen,
    suitePreview,
    setSuitePreview,
    wizardStep,
    setWizardStep,
    wizardDraft,
    setWizardDraft,
  } = useV2ConsoleLocalState();

  const {
    me,
    members,
    personalTokens,
    projects,
    flowLibrary,
    aiConnections,
    security,
    audit,
    projectEnvs,
    projectSuites,
    projectRuns,
    selectedSuite,
    selectedEnv,
    selectedProject,
    scopedRuns,
    selectedRun,
    report,
    role,
    canWrite,
    canAdmin,
    organizations,
    managedUsers,
    stats,
    artifacts,
    videos,
    payloads,
  } = useV2ConsoleDerivedData({
    projectId,
    environmentId,
    suiteId,
    selectedRunId,
  });

  useV2ConsoleEffects({
    section,
    me,
    projects,
    projectId,
    setProjectId,
    environmentId,
    projectEnvs,
    projectSuites,
    suiteId,
    selectedRunId,
    security,
    canAdmin,
    managedUsers,
    organizations,
    setProfileDraft,
    setProjectDraft,
    setCleanupDays,
    setMembershipEdit,
    setSuiteDraft,
    setValidation,
    setError,
    setEnvironmentId,
    setSuiteId,
    setSelectedRunId,
  });

  const { operationPending, ...actions } = useV2ProviderActions({
    projectId,
    setProjectId,
    environmentId,
    setEnvironmentId,
    suiteId,
    setSuiteId,
    setSelectedRunId,
    setTab,
    setError,
    setBusy,
    setNotice,
    projectRuns,
    selectedProject,
    selectedSuite,
    selectedEnv,
    report,
    suiteDraft,
    setSuiteDraft,
    validation,
    setValidation,
    approvedAiPatch,
    setApprovedAiPatch,
    envDraft,
    setEnvDraft,
    projectDraft,
    openApiDraft,
    wizardDraft,
    setWizardOpen,
    setWizardStep,
    setSuitePreview,
    setSuitePreviewOpen,
    flowDraft,
    setFlowDraft,
    aiDraft,
    setAiDraft,
    setAiOutput,
    cleanupDays,
    setCleanupResult,
    me,
    memberDraft,
    setMemberDraft,
    profileDraft,
    setProfileDraft,
    orgDraft,
    setOrgDraft,
    membershipEdit,
    setMembershipEdit,
    tokenDraft,
    setTokenDraft,
  });

  const value: V2ConsoleContextValue = {
      projects,
      projectEnvs,
      projectSuites,
      projectRuns,
      scopedRuns,
      selectedProject,
      selectedSuite,
      selectedEnv,
      selectedRun,
      stats,
      report,
      artifacts,
      videos,
      payloads,
      suiteSearch,
      suiteTypeFilter,
      busy: busy || operationPending,
      error,
      notice,
      role,
      canWrite,
      canAdmin,
      projectId,
      environmentId,
      suiteId,
      selectedRunId,
      tab,
      setTab,
      setSuiteSearch,
      setSuiteTypeFilter,
      openSheet,
      setOpenSheet,
      setProjectId,
      setEnvironmentId,
      setSuiteId,
      setSelectedRunId,
      projectDraft,
      setProjectDraft,
      envDraft,
      setEnvDraft,
      suiteDraft,
      setSuiteDraft,
      validation,
      openApiDraft,
      setOpenApiDraft,
      approvedAiPatch,
      setApprovedAiPatch,
      me,
      members,
      organizations,
      managedUsers,
      memberDraft,
      setMemberDraft,
      profileDraft,
      setProfileDraft,
      orgDraft,
      setOrgDraft,
      membershipEdit,
      personalTokens,
      tokenDraft,
      setTokenDraft,
      aiConnections,
      aiDraft,
      setAiDraft,
      security,
      audit,
      cleanupDays,
      setCleanupDays,
      cleanupResult,
      flowLibrary,
      flowDraft,
      setFlowDraft,
      aiOutput,
      wizardOpen,
      setWizardOpen,
      wizardStep,
      setWizardStep,
      wizardDraft,
      setWizardDraft,
      suitePreviewOpen,
      setSuitePreviewOpen,
      suitePreview,
      ...actions,
  };

  return (
    <V2ConsoleContext.Provider value={value}>
      {children}
    </V2ConsoleContext.Provider>
  );
}

export { useV2Actions, useV2Console, useV2Drafts, useV2Selection } from './useV2Console';
